# Generated by Django 4.2.4 on 2023-08-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sum',
            new_name='sum_order',
        ),
    ]
