# Generated by Django 4.2.4 on 2023-08-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_rename_sum_order_sum_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
