# Generated by Django 4.2.4 on 2023-08-30 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
