# Generated by Django 4.2.4 on 2023-08-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sem_2_1_app', '0004_alter_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
